### ISSUE TITLE
3 tests failing

### ISSUE THREAD

**Issue by jgarte** [lmittmann/clr#3]
Are these tests currently failing for anyone else?

```
test_multiple_strings (clr.test.test_style_builder.StyleBuilderTestCase) ... FAIL
test_single_string (clr.test.test_style_builder.StyleBuilderTestCase) ... FAIL
test_style_chaining (clr.test.test_style_builder.StyleBuilderTestCase) ... FAIL

======================================================================
FAIL: test_multiple_strings (clr.test.test_style_builder.StyleBuilderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-style-1.0.0.drv-0/source/clr/test/test_style_builder.py", line 16, in test_multiple_strings
    self.assertTrue('31' in clr.red('test1', 'test2'))
AssertionError: False is not true

======================================================================
FAIL: test_single_string (clr.test.test_style_builder.StyleBuilderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-style-1.0.0.drv-0/source/clr/test/test_style_builder.py", line 11, in test_single_string
    self.assertTrue('31' in clr.red('test'))
AssertionError: False is not true

======================================================================
FAIL: test_style_chaining (clr.test.test_style_builder.StyleBuilderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-style-1.0.0.drv-0/source/clr/test/test_style_builder.py", line 20, in test_style_chaining
    self.assertTrue('31;47;1' in clr.red.bgWhite.bold('test'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=3)

```

**Comment by lmittmann** [comment]
Tests are green for me

**Comment by jgarte** [comment]
> Tests are green for me

Thanks for the reply!

How did you run the test suite?

**Comment by lmittmann** [comment]
`python -m unittest` on 2.7 or 3.x

**Comment by jgarte** [comment]
Do you happen to know if tests are also passing for this tag? https://github.com/lmittmann/style/releases/tag/v1.0.0

I'm packaging `style` for [GNU Guix](guix.gnu.org): https://issues.guix.gnu.org/55108

I packaged the version in PyPi in the above 55108 ticket for Guix

Should I package `v1.0.0` or some other commit?

What do you suggest?

**Comment by lmittmann** [comment]
Is there any reason that you don't want to use the latest version `v1.1.6` (cb65bde8)?

**Comment by jgarte** [comment]
I didn't see it listed in the available tags on the GitHub UI:

https://github.com/lmittmann/style/tags

and after cloning

```
 $ git tag
v1.0.0
```

Where can I find the source locations for that tag that contains the tests?

**Comment by lmittmann** [comment]
I tagged the latest release `v1.1.6`.

https://github.com/lmittmann/style/releases/tag/v1.1.6
